# Generated by Django 3.2.5 on 2021-07-31 13:00

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DamageType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
            ],
        ),
        migrations.RenameField(
            model_name='championwinrate',
            old_name='champion',
            new_name='championID',
        ),
        migrations.RenameField(
            model_name='talent',
            old_name='champion',
            new_name='championID',
        ),
        migrations.RemoveField(
            model_name='card',
            name='rank',
        ),
        migrations.AddField(
            model_name='card',
            name='base',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=8),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='card',
            name='card_image',
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name='card',
            name='championID',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='mainApp.champion'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='card',
            name='increase',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=8),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='card',
            name='talent',
            field=models.CharField(default='aa', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='card',
            name='type',
            field=models.CharField(default='aa', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='champion',
            name='champion_image',
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name='championwinrate',
            name='updated_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='talent',
            name='description',
            field=models.CharField(default='aa', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='talent',
            name='talent_image',
            field=models.URLField(null=True),
        ),
        migrations.CreateModel(
            name='Ability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('description', models.CharField(max_length=50)),
                ('summary', models.CharField(max_length=50)),
                ('ability_image', models.URLField(null=True)),
                ('championID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainApp.champion')),
                ('damageType', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainApp.damagetype')),
            ],
        ),
    ]
