# Generated by Django 3.2.5 on 2021-07-31 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0002_auto_20210731_1600'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='long_name',
            field=models.CharField(default='aa', max_length=21),
            preserve_default=False,
        ),
    ]
