# Generated by Django 3.2.5 on 2021-07-31 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0004_damagetype_slug_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='champion',
            name='description',
            field=models.CharField(max_length=900),
        ),
    ]
