# Generated by Django 3.2.5 on 2021-07-31 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0005_alter_champion_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ability',
            name='summary',
        ),
    ]
