# Generated by Django 3.2.5 on 2021-07-31 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0006_remove_ability_summary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ability',
            name='description',
            field=models.CharField(max_length=600),
        ),
        migrations.AlterField(
            model_name='ability',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
