# Generated by Django 3.2.5 on 2021-07-31 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0007_auto_20210731_1748'),
    ]

    operations = [
        migrations.AddField(
            model_name='champion',
            name='API_ID',
            field=models.IntegerField(default=0),
        ),
    ]
