# Generated by Django 3.2.5 on 2021-07-31 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0009_auto_20210731_1936'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card',
            name='talent',
        ),
    ]
