# Generated by Django 3.2.5 on 2021-07-31 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0010_remove_card_talent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='name',
            field=models.CharField(max_length=35),
        ),
        migrations.AlterField(
            model_name='talent',
            name='name',
            field=models.CharField(max_length=35),
        ),
    ]
