# Generated by Django 3.2.5 on 2021-07-31 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0011_auto_20210731_1952'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='name',
            field=models.CharField(max_length=55),
        ),
        migrations.AlterField(
            model_name='card',
            name='type',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='talent',
            name='name',
            field=models.CharField(max_length=55),
        ),
        migrations.AlterField(
            model_name='talent',
            name='type',
            field=models.CharField(max_length=50),
        ),
    ]
