# Generated by Django 3.2.5 on 2021-07-31 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0012_auto_20210731_1954'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='type',
            field=models.CharField(max_length=75),
        ),
        migrations.AlterField(
            model_name='talent',
            name='type',
            field=models.CharField(max_length=75),
        ),
    ]
