# Generated by Django 3.2.5 on 2021-08-01 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0013_auto_20210731_1955'),
    ]

    operations = [
        migrations.RenameField(
            model_name='card',
            old_name='base',
            new_name='base1',
        ),
        migrations.RenameField(
            model_name='card',
            old_name='increase',
            new_name='increase1',
        ),
        migrations.AddField(
            model_name='card',
            name='base2',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=8),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='card',
            name='increase2',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=8),
            preserve_default=False,
        ),
    ]
